code --install-extension aaron-bond.better-comments
code --install-extension bradlc.vscode-tailwindcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension foxundermoon.shell-format
code --install-extension GitHub.github-vscode-theme
code --install-extension Goopware.raythis
code --install-extension humao.rest-client
code --install-extension meganrogge.template-string-converter
code --install-extension mikestead.dotenv
code --install-extension mjmlio.vscode-mjml
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension PKief.material-icon-theme
code --install-extension Prisma.prisma
code --install-extension PulkitGangwar.nextjs-snippets
code --install-extension ue.alphabetical-sorter
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension wix.vscode-import-cost
